apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ow6i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-ow6i@sha256:7061138160a2ce853fa414ba51e8d0950ab94450a5d24a98c30cdcecd0839cea
        name: my-nodejs
        resources: {}
status: {}
